# WASEEM dataset

In [2]:
import pandas as pd

df = pd.read_csv('../datasets/waseem/tweet_dataset.csv', sep='\t', header=None)[0]
print(df.head())
print(len(df))
df.to_csv('../datasets/waseem/tweet_dataset_ids.txt', header=None, index=False)

In [19]:
%run -i "tweetdownload_tweepy.py" \
# -i '../datasets/waseem/tweet_dataset.csv' \
# -o '../datasets/waseem/extracted_texts.txt' \
# --consumerkey 'zg5ZoWps3wHjfAwjmR5mQHjKW' \
# --consumersecret 'dsCwQ2Da7ajUTj4IWHTEUY0owJ0GxZOiGVM9Lr0529RqEiRk31' \
# --accesstoken '936005824111026176-WfU8grlXW2ogKis6vmB1rC6dcAquaCO' \
# --accesssecret 'nJZBE8h2Y8aloEZnJ4Fuwq3MFJvf6E4BVRx41lwbXqpyc'


done till 0 77
done till 90 78
done till 180 80
done till 270 83
done till 360 85
done till 450 83
done till 540 85
done till 630 75
done till 720 80
done till 810 84
done till 900 79
done till 990 83
done till 1080 80
done till 1170 84
done till 1260 81
done till 1350 84
done till 1440 82
done till 1530 82
done till 1620 84
done till 1710 77
done till 1800 82
done till 1890 85
done till 1980 87
done till 2070 80
done till 2160 83
done till 2250 77
done till 2340 83
done till 2430 81
done till 2520 85
done till 2610 84
done till 2700 81
done till 2790 72
done till 2880 82
done till 2970 72
done till 3060 79
done till 3150 80
done till 3240 82
done till 3330 81
done till 3420 85
done till 3510 82
done till 3600 84
done till 3690 81
done till 3780 85
done till 3870 82
done till 3960 81
done till 4050 81
done till 4140 82
done till 4230 86
done till 4320 82
done till 4410 85
done till 4500 80
done till 4590 81
done till 4680 80
done till 4770 79
done till 4860 80
done till 4950 81
done ti

In [2]:
from pprint import pprint
import pandas as pd
import pickle as pkl

# GET tweet texts extracted from ids
d = pkl.load(open('../datasets/waseem/output_status_list.pkl', 'rb'))
dict_texts = {}
for status in d:
    s = status._json
    pprint(s)
    break
    dict_texts[s['id']] = s['text']
# GET expert label and annotator lables
# l = pd.read_csv('../datasets/waseem/tweet_dataset.csv', sep='\t', header=None)

{'contributors': None,
 'coordinates': None,
 'created_at': 'Mon Feb 23 20:28:36 +0000 2015',
 'entities': {'hashtags': [],
              'symbols': [],
              'urls': [],
              'user_mentions': [{'id': 297535251,
                                 'id_str': '297535251',
                                 'indices': [0, 14],
                                 'name': 'The Ritual Tree',
                                 'screen_name': 'OutworldDOTA2'}]},
 'favorite_count': 0,
 'favorited': False,
 'geo': None,
 'id': 569957017655226369,
 'id_str': '569957017655226369',
 'in_reply_to_screen_name': 'OutworldDOTA2',
 'in_reply_to_status_id': 569956825057120256,
 'in_reply_to_status_id_str': '569956825057120256',
 'in_reply_to_user_id': 297535251,
 'in_reply_to_user_id_str': '297535251',
 'is_quote_status': False,
 'lang': 'en',
 'place': None,
 'retweet_count': 0,
 'retweeted': False,
 'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
 'text': '@Outwor

In [90]:
print(l.head(1))

from time import sleep
from IPython.display import clear_output, display

import numpy as np
label_map = {'racism':0, 'sexism':1, 'both':2, 'neither':3}

tweet_ids = l[0]
tweet_texts = [dict_texts[tid] if tid in dict_texts else np.inf for tid in tweet_ids]

def map_func(x):
    if pd.isnull(x):
        return x
    elif x=='link':
        return np.NaN
    elif x in label_map:
        return int(label_map[x])
    else:
        return x
    
for i in range(1,len(l.columns)):
    clear_output(wait=True)
    print('>> i={}'.format(i))
    l[i] = l[i].apply(lambda x: map_func(x))
    l[i] = l[i].dropna().apply(lambda x: str(int(x)))
    # break
l.head(5)

>> i=1091


0    1    2    3    4    5    6    7    8    9     ... 1082  \
0  597576902212063232    3    3    3    3  NaN  NaN  NaN  NaN  NaN  ...  NaN   
1  565586175864610817    3    3    3    3  NaN  NaN  NaN  NaN  NaN  ...  NaN   
2  563881580209246209    3    3    3    3  NaN  NaN  NaN  NaN  NaN  ...  NaN   
3  595380689534656512    3    3    1    3  NaN  NaN  NaN  NaN  NaN  ...  NaN   
4  563757610327748608    3    3    3    3  NaN  NaN  NaN  NaN  NaN  ...  NaN   

  1083 1084 1085 1086 1087 1088 1089 1090 1091  
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[5 rows x 1092 columns]

In [252]:
l.to_csv('../datasets/waseem/tweet_dataset_numbered.csv', sep='\t', header=None, index=False)


In [254]:
l = pd.read_csv('../datasets/waseem/tweet_dataset_numbered.csv', sep='\t', header=None)

majority_labels = []
print(l.head())
for i, row in l.iterrows():
    clear_output(wait=True)
    print('>> i={}'.format(i))
    vals = list(row[2:].dropna().values)
    if vals == []:
        maj = row[1]  # expert_label
    else:
        maj = max(set(vals), key = vals.count)
    majority_labels.append(int(maj))
    # break
print(majority_labels[0:25])
# print(l.head(1))


>> i=6908
[3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 0, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3]


In [255]:
new_df = pd.DataFrame()
new_df['id'] = l[0]
new_df['text'] = tweet_texts
new_df['gt_label'] = np.array(l[1], dtype=np.int32)
new_df['label'] = majority_labels
new_df['vlabel'] = (new_df['gt_label'] == new_df['label'])*1
new_df.head()

id                                               text  \
0  597576902212063232  Cisco had to deal with a fat cash payout to th...   
1  565586175864610817  @MadamPlumpette I'm decent at editing, no worr...   
2  563881580209246209  @girlziplocked will read. gotta go afk for a b...   
3  595380689534656512  guys. show me the data. show me your github. t...   
4  563757610327748608  @tpw_rules nothings broken. I was just driving...   

   gt_label  label  vlabel  
0         3      3       1  
1         3      3       1  
2         3      3       1  
3         3      3       1  
4         3      3       1

In [256]:
len(new_df)

6909

In [257]:
print((new_df.gt_label != new_df.label).sum() / 6909 * 100)

13.98176291793313


In [258]:
for i in range(0,4):
    print((new_df.label == i).sum())

227
1274
19
5389


In [259]:
# mislabled in each class (acc to given label)
for i in range(0, 4):
    test = new_df[new_df['label'] == i]
    # print(test.head())
    print((test.vlabel == 0).sum(), len(test)) # / len(test)* 100.0)

183 227
546 1274
10 19
227 5389


In [260]:
mat = np.zeros((4,4))
for i in range(0, 4):
    test = new_df[new_df['gt_label'] == i]
    print(len(test))
    for j in range(0, 4):
        # print(i, j, (test.label == j).sum())
        mat[i][j] = (test.label == j).sum() / len(test) * 100
        # print(mat[i][j])
print(np.round(mat, 2))

98
911
50
5850
[[44.9   3.06  0.   52.04]
 [ 2.52 79.91  0.33 17.23]
 [20.   24.   18.   38.  ]
 [ 2.56  9.08  0.12 88.24]]


In [261]:
len(new_df)

6909

In [263]:
from sklearn.model_selection import train_test_split
ind = np.arange(len(new_df))
ind_train, ind_test, gt_train, gt_test = train_test_split(ind, np.array(new_df.gt_label), test_size=0.20, random_state=42, stratify=new_df.gt_label)

print(ind_train)
print(ind_test)
print(gt_train)
print(gt_test)

print(len(ind_train))
print(len(ind_test))

[2729 3918 3258 ... 4041  563 4686]
[6753 4890 4626 ... 2827 5219 1513]
[3 3 0 ... 3 3 3]
[3 3 3 ... 2 3 3]
5527
1382


In [265]:

a = np.zeros(len(new_df), np.int32)
a[ind_test] = 1
new_df['test'] = a

print(new_df.test.sum())

for i in range(0,4):
    test = new_df[new_df.test == 1]
    print((test.gt_label == i).sum() / len(test) * 100)
    
# for i in range(0,4):
#     test = new_df[new_df.test == 0]
#     print((test.gt_label == i).sum() / len(test) * 100)

1382
1.447178002894356
13.16931982633864
0.723589001447178
84.65991316931982


In [266]:
print(new_df.columns)
new_df.head()
new_df.label.values

Index(['id', 'text', 'gt_label', 'label', 'vlabel', 'test'], dtype='object')


array([3, 3, 3, ..., 3, 3, 3])

In [289]:
len(new_df)

tab_removed_text = []
for i, text in enumerate(new_df['text']):
    clear_output(True)
    print('>>i = {}'.format(i))
    s=str(text).replace('\t', ' ')
    s=s.replace('\n', ' ')
    s=s.replace('\r', ' ')
    tab_removed_text.append(s)
new_df['new_text'] = tab_removed_text
print(new_df.head())

>>i = 6908
                   id                                               text  \
0  597576902212063232  Cisco had to deal with a fat cash payout to th...   
1  565586175864610817  @MadamPlumpette I'm decent at editing, no worr...   
2  563881580209246209  @girlziplocked will read. gotta go afk for a b...   
3  595380689534656512  guys. show me the data. show me your github. t...   
4  563757610327748608  @tpw_rules nothings broken. I was just driving...   

   gt_label  label  vlabel  test  \
0         3      3       1     0   
1         3      3       1     1   
2         3      3       1     1   
3         3      3       1     0   
4         3      3       1     0   

                                            new_text  
0  Cisco had to deal with a fat cash payout to th...  
1  @MadamPlumpette I'm decent at editing, no worr...  
2  @girlziplocked will read. gotta go afk for a b...  
3  guys. show me the data. show me your github. t...  
4  @tpw_rules nothings broken. I was jus

In [290]:
new_df['text'] = new_df['new_text']
del new_df['new_text']
print(len(new_df))

6909


In [291]:
import csv
new_df.to_csv('../datasets/waseem/waseem_data.csv', sep='\t', index=False) # , quoting=csv.QUOTE_NONNUMERIC)

In [292]:
new_df[new_df['test'] == 1].to_csv('../datasets/waseem/waseem_test.csv', sep='\t', index=False)
new_df[new_df['test'] == 0].to_csv('../datasets/waseem/waseem_train.csv', sep='\t', index=False)



In [247]:
ind = np.arange(len(new_df))
_, ind_vtrain, _, _ = train_test_split(ind_train, np.array(new_df.iloc[ind_train].gt_label), test_size=0.15, random_state=42, stratify=new_df.iloc[ind_train].gt_label)

print(len(ind_vtrain))

830


In [294]:
5527 +1382

6909