In [17]:
# CHANGE CODE FOR HEADER=? and COLUMNNAMES=? and LABEL/GT_LABEL

%run -i 'bert_classifier.py' \
--nb_cls 4 --max_seqlen 128 --batch_size 16 --epochs 6 --lr 2e-5 --weight_decay 0.01 \
--input_train '/home/krsharma/labelnoise/datasets/waseem/waseem_train.csv' \
--input_test '/home/krsharma/labelnoise/datasets/waseem/waseem_test.csv' \
--results_dir '/home/krsharma/labelnoise/trained_models/waseem' \
--model_file_name 'model_epoch.pt' \
--emb_file_name 'emb_epoch.txt' \
--mode 'train'

Namespace(batch_size=16, emb_file_name='emb_epoch.txt', epochs=6, input_test='/home/krsharma/labelnoise/datasets/waseem/waseem_test.csv', input_train='/home/krsharma/labelnoise/datasets/waseem/waseem_train.csv', lr=2e-05, max_seqlen=128, mode='train', model_file_name='model_epoch.pt', nb_cls=4, results_dir='/home/krsharma/labelnoise/trained_models/waseem', weight_decay=0.01)
starting program..
GeForce GTX 1080 Ti
starting data loading..
[3 3 3 ... 3 3 3]
[0 1 2 3]
<class 'numpy.ndarray'>
read data: 5526
[3 3 3 ... 3 3 1]
[0 1 2 3]
<class 'numpy.ndarray'>
read data: 1381
loading pretrained model..


Epoch:   0%|          | 0/6 [00:00<?, ?it/s]

starting model fine-tuning..
computed train class_weights: [  7.675        1.3517612  115.125        0.32038498]
Train loss: 0.8928755925311519
Test Accuracy: 0.8683908045977011


Epoch:  17%|█▋        | 1/6 [01:19<06:37, 79.46s/it]

Train loss: 0.6494366967178493
Test Accuracy: 0.8570402298850575


Epoch:  33%|███▎      | 2/6 [02:38<05:17, 79.35s/it]

Train loss: 0.4965471674855045
Test Accuracy: 0.8531609195402298


Epoch:  50%|█████     | 3/6 [03:58<03:58, 79.43s/it]

Train loss: 0.39615959017349117
Test Accuracy: 0.869683908045977


Epoch:  67%|██████▋   | 4/6 [05:17<02:38, 79.50s/it]

Train loss: 0.34095842507802426
Test Accuracy: 0.8748563218390805


Epoch:  83%|████████▎ | 5/6 [06:37<01:19, 79.41s/it]

Train loss: 0.2828776599769346
Test Accuracy: 0.8669540229885058


Epoch: 100%|██████████| 6/6 [07:55<00:00, 79.20s/it]


create results dir if not exists..
finished model evaluation and saving..
Test Accuracy: 0.8669540229885058
('              precision    recall  f1-score   support\n'
 '\n'
 '           0       0.38      0.38      0.38        47\n'
 '           1       0.66      0.94      0.78       252\n'
 '           2       1.00      0.14      0.25         7\n'
 '           3       0.97      0.88      0.92      1075\n'
 '\n'
 '    accuracy                           0.87      1381\n'
 '   macro avg       0.75      0.58      0.58      1381\n'
 'weighted avg       0.89      0.87      0.87      1381\n')
matthews corr coeff: 0.6821320575216033
finished saving representations..
finished program.


In [22]:
# USE THE ABOVE MODEL TRAINED ON LABEL -> CHANGE CODE TO TAKE GT_LABELS FOR EVAL

%run -i 'bert_classifier.py' \
--nb_cls 4 --max_seqlen 128 --batch_size 16 --epochs 6 --lr 2e-5 --weight_decay 0.01 \
--input_train '/home/krsharma/labelnoise/datasets/waseem/waseem_train.csv' \
--input_test '/home/krsharma/labelnoise/datasets/waseem/waseem_test.csv' \
--results_dir '/home/krsharma/labelnoise/trained_models/waseem' \
--model_file_name 'model_epoch.pt' \
--emb_file_name 'discard_emb_epoch.txt' \
--mode 'test'

Namespace(batch_size=16, emb_file_name='discard_emb_epoch.txt', epochs=6, input_test='/home/krsharma/labelnoise/datasets/waseem/waseem_test.csv', input_train='/home/krsharma/labelnoise/datasets/waseem/waseem_train.csv', lr=2e-05, max_seqlen=128, mode='test', model_file_name='model_epoch.pt', nb_cls=4, results_dir='/home/krsharma/labelnoise/trained_models/waseem', weight_decay=0.01)
starting program..
GeForce GTX 1080 Ti
starting data loading..
[3 3 3 ... 3 3 3]
[0 1 2 3]
<class 'numpy.ndarray'>
read data: 5527
[3 3 3 ... 3 3 3]
[0 1 2 3]
<class 'numpy.ndarray'>
read data: 1382
loading pretrained model..
loading saved fine-tuned model weights..
create results dir if not exists..
finished model evaluation..
Test Accuracy: 0.8215996168582376
('              precision    recall  f1-score   support\n'
 '\n'
 '           0       0.26      0.60      0.36        20\n'
 '           1       0.46      0.91      0.62       182\n'
 '           2       0.00      0.00      0.00        10\n'
 '       

In [23]:
# FEAT EXT

%run -i 'bert_classifier.py' \
--nb_cls 4 --max_seqlen 128 --batch_size 16 --epochs 6 --lr 2e-5 --weight_decay 0.01 \
--input_train '/home/krsharma/labelnoise/datasets/waseem/waseem_train.csv' \
--input_test '/home/krsharma/labelnoise/datasets/waseem/waseem_test.csv' \
--results_dir '/home/krsharma/labelnoise/trained_models/waseem' \
--model_file_name 'model_epoch.pt' \
--emb_file_name 'emb_epoch.txt' \
--mode 'ext'

Namespace(batch_size=16, emb_file_name='emb_epoch.txt', epochs=6, input_test='/home/krsharma/labelnoise/datasets/waseem/waseem_test.csv', input_train='/home/krsharma/labelnoise/datasets/waseem/waseem_train.csv', lr=2e-05, max_seqlen=128, mode='ext', model_file_name='model_epoch.pt', nb_cls=4, results_dir='/home/krsharma/labelnoise/trained_models/waseem', weight_decay=0.01)
starting program..
GeForce GTX 1080 Ti
starting data loading..
[3 3 3 ... 3 3 3]
[0 1 2 3]
<class 'numpy.ndarray'>
read data: 5527
[3 3 3 ... 3 3 3]
[0 1 2 3]
<class 'numpy.ndarray'>
read data: 1382
loading pretrained model..
loading saved fine-tuned model weights..
create results dir if not exists..
finished saving representations..
finished program.


In [4]:
# LOGITS SAVE

%run -i 'bert_classifier.py' \
--nb_cls 4 --max_seqlen 128 --batch_size 16 --epochs 6 --lr 2e-5 --weight_decay 0.01 \
--input_train '/home/krsharma/labelnoise/datasets/waseem/waseem_train.csv' \
--input_test '/home/krsharma/labelnoise/datasets/waseem/waseem_test.csv' \
--results_dir '/home/krsharma/labelnoise/trained_models/waseem' \
--model_file_name 'model_epoch.pt' \
--logits_file_name 'logits_epoch.txt' \
--mode 'class_filtering'

Namespace(batch_size=16, emb_file_name=None, epochs=6, input_test='/home/krsharma/labelnoise/datasets/waseem/waseem_test.csv', input_train='/home/krsharma/labelnoise/datasets/waseem/waseem_train.csv', logits_file_name='logits_epoch.txt', lr=2e-05, max_seqlen=128, mode='class_filtering', model_file_name='model_epoch.pt', nb_cls=4, results_dir='/home/krsharma/labelnoise/trained_models/waseem', weight_decay=0.01)
starting program..
GeForce GTX 1080 Ti
starting data loading..
[3 3 3 ... 3 3 3]
[0 1 2 3]
<class 'numpy.ndarray'>
read data: 5527
[3 3 3 ... 3 3 1]
[0 1 2 3]
<class 'numpy.ndarray'>
read data: 1382
loading pretrained model..
loading saved fine-tuned model weights..
create results dir if not exists..
finish saving logits for classification filtering baseline..
Test Accuracy: 0.928106936416185
finished program.


In [19]:
# UPPER BOUND (TRAIN ON GT_LABEL)

%run -i 'bert_classifier.py' \
--nb_cls 4 --max_seqlen 128 --batch_size 16 --epochs 6 --lr 2e-5 --weight_decay 0.01 \
--input_train '/home/krsharma/labelnoise/datasets/waseem/waseem_train.csv' \
--input_test '/home/krsharma/labelnoise/datasets/waseem/waseem_test.csv' \
--results_dir '/home/krsharma/labelnoise/trained_models/waseem' \
--model_file_name 'upper_model_epoch.pt' \
--emb_file_name 'upper_emb_epoch.txt' \
--mode 'train'

Namespace(batch_size=16, emb_file_name='upper_emb_epoch.txt', epochs=6, input_test='/home/krsharma/labelnoise/datasets/waseem/waseem_test.csv', input_train='/home/krsharma/labelnoise/datasets/waseem/waseem_train.csv', lr=2e-05, max_seqlen=128, mode='train', model_file_name='upper_model_epoch.pt', nb_cls=4, results_dir='/home/krsharma/labelnoise/trained_models/waseem', weight_decay=0.01)
starting program..
GeForce GTX 1080 Ti
starting data loading..
[3 3 3 ... 3 3 3]
[0 1 2 3]
<class 'numpy.ndarray'>
read data: 5526
[3 3 3 ... 3 3 3]
[0 1 2 3]
<class 'numpy.ndarray'>
read data: 1381
loading pretrained model..


Epoch:   0%|          | 0/6 [00:00<?, ?it/s]

starting model fine-tuning..
computed train class_weights: [17.711538   1.8950617 34.5375     0.2952554]
Train loss: 1.0236274089255084
Test Accuracy: 0.8462643678160919


Epoch:  17%|█▋        | 1/6 [01:19<06:36, 79.38s/it]

Train loss: 0.7730987268376213
Test Accuracy: 0.8764367816091954


Epoch:  33%|███▎      | 2/6 [02:38<05:17, 79.41s/it]

Train loss: 0.6946803752462126
Test Accuracy: 0.8554597701149425


Epoch:  50%|█████     | 3/6 [03:58<03:58, 79.37s/it]

Train loss: 0.5816665033384555
Test Accuracy: 0.8504310344827586


Epoch:  67%|██████▋   | 4/6 [05:18<02:39, 79.57s/it]

Train loss: 0.5249410337321676
Test Accuracy: 0.8360632183908046


Epoch:  83%|████████▎ | 5/6 [06:37<01:19, 79.63s/it]

Train loss: 0.4530479846376861
Test Accuracy: 0.8748563218390805


Epoch: 100%|██████████| 6/6 [07:57<00:00, 79.60s/it]


create results dir if not exists..
finished model evaluation and saving..
Test Accuracy: 0.8748563218390805
('              precision    recall  f1-score   support\n'
 '\n'
 '           0       0.50      0.65      0.57        20\n'
 '           1       0.56      0.80      0.66       182\n'
 '           2       0.50      0.20      0.29        10\n'
 '           3       0.96      0.90      0.93      1169\n'
 '\n'
 '    accuracy                           0.88      1381\n'
 '   macro avg       0.63      0.64      0.61      1381\n'
 'weighted avg       0.90      0.88      0.88      1381\n')
matthews corr coeff: 0.6059304968022828
finished saving representations..
finished program.
