In [37]:
import pickle as pkl
import pandas as pd
import numpy as np

In [38]:
# datadir = '/home/krsharma/ClassificationImageText/trained_models/food101n_20e/robustnoiserank/eccvR_food-256d_emb/'
# datapkl = ['d_00000_303590x256.pickle']
# labelfile = datadir + 'eluo_food101n_everstore_handle_with_label_and_type.csv'

datadir = '/home/krsharma/ClassificationImageText/trained_models/clothing1m_10e/robustnoiserank/eccvR_clothing-256d_emb/'
datapkl = ['d_00000_781250x256.pickle', 'd_00001_236739x256.pickle']
labelfile = datadir + 'eluo_clothing1m_everstore_handle_with_label_and_type.csv'

# Format extracted 256d embeddings from pkl to tsv

In [42]:
d0_list = []  # everstore 
d1_list = []  # embedding
for p in datapkl:
    di = pkl.load(open(datadir + p, 'rb'))
    d0_list.append(di[0]); d1_list.append(di[1])

d0 = np.vstack(d0_list)
print(d0.shape)

d1 = np.hstack(d1_list)
print(d1.shape)

(1017989, 256)
(1017989,)


In [44]:
df = pd.DataFrame()
sid = np.arange(d0.shape[0])
eid = d1
df['sid'] = sid
df['eid'] = eid
df.head(), len(eid), len(sid)

(   sid                                   eid
 0    0  GIPsEAWbm8NMUVECAOkij2nvJTQvbiMZAAAB
 1    1  GKHrDQWieLFkLXkJAIaDGKAkHzFAbiMZAAAB
 2    2  GIubAgXFwnwkyr4BAIvraNOp1D9jbiMZAAAB
 3    3  GN9QEgX1E50yB4IJAOP6qTt1_CNebiMZAAAB
 4    4  GNKBDAV3PCNpAQgBAGejLVTPZyFrbiMZAAAB, 1017989, 1017989)

In [45]:
ldf = pd.read_csv(labelfile, header=None)
ldf.head()

0                          1  \
0   images/0/53/260975258,2323897053.jpg   260975258,2323897053.jpg   
1  images/3/61/2976764135,2716435361.jpg  2976764135,2716435361.jpg   
2  images/9/51/2289770356,3952390951.jpg  2289770356,3952390951.jpg   
3   images/9/46/430097811,2005980946.jpg   430097811,2005980946.jpg   
4   images/4/53/3469714287,432026453.jpg   3469714287,432026453.jpg   

                                      2        3   4    5           6     7  
0  GOotBwWSElDZtFsAAGshNhrA9hdEbiMZAAAB   Jacket   7  0.0  2020-02-04   val  
1  GProEQWGvjYQw6kAAK1c8Yf51zpabiMZAAAB   Jacket   7  0.0  2020-02-04   val  
2  GO3cCwUP8P3SX28AANt4RxtOHgYmbiMZAAAB  T-Shirt   0  NaN  2020-02-04  test  
3  GCAlEQWVFrN0SpECAJkqle41WVwlbiMZAAAB     Vest  12  NaN  2020-02-04  test  
4  GCKSEQVFfl_GL3kAANhTTwICHxdGbiMZAAAB    Dress  11  NaN  2020-02-04  test

In [46]:
np.unique(ldf[4], return_counts=True)[1].mean()  # .max() # .mean()

72713.64285714286

In [47]:
# 30 (min), 40 (mean), 50 (max) vs 100 (min), 190 (mean), 211 (max)
K = np.sqrt(2012)
print(K)

K = np.sqrt(72713/2)
print(K)

K = np.sqrt(5344)
print(K)

44.85532298401161
190.6738052276715
73.10266752998827


In [48]:
ldict = dict(zip(ldf[2], ldf[4]))
df['label'] = df['eid'].apply(lambda x: ldict[x])
df.head()

sid                                   eid  label
0    0  GIPsEAWbm8NMUVECAOkij2nvJTQvbiMZAAAB     13
1    1  GKHrDQWieLFkLXkJAIaDGKAkHzFAbiMZAAAB      0
2    2  GIubAgXFwnwkyr4BAIvraNOp1D9jbiMZAAAB      8
3    3  GN9QEgX1E50yB4IJAOP6qTt1_CNebiMZAAAB     12
4    4  GNKBDAV3PCNpAQgBAGejLVTPZyFrbiMZAAAB      7

In [50]:
emb = np.vstack([d0]) # , d2[0]])

In [51]:
df['emb'] = list(np.round(emb, 3))
df.head()

sid                                   eid  label  \
0    0  GIPsEAWbm8NMUVECAOkij2nvJTQvbiMZAAAB     13   
1    1  GKHrDQWieLFkLXkJAIaDGKAkHzFAbiMZAAAB      0   
2    2  GIubAgXFwnwkyr4BAIvraNOp1D9jbiMZAAAB      8   
3    3  GN9QEgX1E50yB4IJAOP6qTt1_CNebiMZAAAB     12   
4    4  GNKBDAV3PCNpAQgBAGejLVTPZyFrbiMZAAAB      7   

                                                 emb  
0  [0.63, 1.031, 0.156, -0.34, 0.3, 0.817, -0.64,...  
1  [-0.106, 0.228, -0.458, 0.02, 0.057, -0.445, -...  
2  [0.068, -0.239, -0.313, 0.343, -0.332, -0.167,...  
3  [0.298, 0.186, 0.239, -0.263, 0.225, 0.212, 0....  
4  [-0.625, -0.125, 0.104, -0.508, -0.798, -0.442...

In [52]:
df['emb'] = df['emb'].apply(lambda x: ",".join(map(str, x)))

In [53]:
df.head()

sid                                   eid  label  \
0    0  GIPsEAWbm8NMUVECAOkij2nvJTQvbiMZAAAB     13   
1    1  GKHrDQWieLFkLXkJAIaDGKAkHzFAbiMZAAAB      0   
2    2  GIubAgXFwnwkyr4BAIvraNOp1D9jbiMZAAAB      8   
3    3  GN9QEgX1E50yB4IJAOP6qTt1_CNebiMZAAAB     12   
4    4  GNKBDAV3PCNpAQgBAGejLVTPZyFrbiMZAAAB      7   

                                                 emb  
0  0.63,1.031,0.156,-0.34,0.3,0.817,-0.64,0.377,-...  
1  -0.106,0.228,-0.458,0.02,0.057,-0.445,-0.051,-...  
2  0.068,-0.239,-0.313,0.343,-0.332,-0.167,-0.342...  
3  0.298,0.186,0.239,-0.263,0.225,0.212,0.322,-0....  
4  -0.625,-0.125,0.104,-0.508,-0.798,-0.442,-0.28...

In [54]:
df.to_csv(datadir + 'cleannet_all_256d.tsv', sep='\t', index=False, header=None)

# Prototype Selection (bash script)

In [ ]:
datadir='/home/krsharma/ClassificationImageText/trained_models/clothing1m_10e/robustnoiserank/eccvR_clothing-256d_emb'
codedir='/home/krsharma/ClassificationImageText/clean-net'
outdir=$datadir/

python $codedir/util/convert_data.py --split=all \
--class_list=$datadir/cleannet_classnames.txt \
--data_path=$datadir/cleannet_all_256d.tsv \
--output_dir=$datadir

for num in 190 100 500; do  # food - 40 30 50 100
    mkdir $datadir/ref$num
    
    python $codedir/util/find_reference.py \
    --class_list=$datadir/cleannet_classnames.txt \
    --input_npy=$datadir/all.npy \
    --output_dir=$datadir/ref$num \
    --num_ref=$num --img_dim=256
    
    mv $datadir/ref$num/ref.npy $datadir/ref_$num.npy
done

# Format ref numpy to tsv

In [56]:
NR_list = [100, 190, 500]

for NR in NR_list:
    path = datadir + "ref_{}.npy".format(NR)

    ref = np.load(path)

    print(ref.shape)
    
    
    df = pd.DataFrame()

    def join_str(ci):
        return ",".join(map(str, ci))

    labels = []
    vecs = []
    for classname, c in enumerate(ref):
        labels += [int(classname)] * len(c)
        vecs += [join_str(ci) for ci in np.round(c, 3)]
    labels = np.array(labels, dtype=np.int32)
    df['id'] = np.arange(len(labels))
    df['img'] = np.arange(len(labels))
    df['labels'] = labels
    df['feats'] = vecs

    print(df.head())
    
    df.to_csv(datadir + 'ref_{}.tsv'.format(NR), sep='\t', header=None, index=False)
    

(14, 100, 256)
   id  img  labels                                              feats
0   0    0       0  -0.306,0.16,0.034,-0.139,0.092,-0.45,0.136,-0....
1   1    1       0  -0.378,0.551,-0.193,-0.24,0.08,-0.645,0.202,-0...
2   2    2       0  -0.6,0.222,-0.028,-0.268,-0.003,-0.718,0.304,-...
3   3    3       0  -0.083,-0.15,0.219,-0.054,0.156,-0.026,0.301,-...
4   4    4       0  -0.132,0.119,-0.151,-0.098,0.101,-0.23,0.124,-...
(14, 190, 256)
   id  img  labels                                              feats
0   0    0       0  -0.394,-0.017,0.432,-0.273,0.086,-0.416,0.627,...
1   1    1       0  -0.277,0.322,-0.169,-0.137,0.078,-0.578,0.19,-...
2   2    2       0  -0.512,0.156,-0.14,-0.146,0.053,-0.779,0.225,-...
3   3    3       0  -0.184,-0.17,-0.086,0.115,0.128,-0.184,0.1,-0....
4   4    4       0  0.027,-0.098,0.231,-0.043,0.281,0.019,0.352,-0...
(14, 500, 256)
   id  img  labels                                              feats
0   0    0       0  -0.068,0.208,-0.076,-0.02

# Run Robust Noise Rank (conda activate faiss, bash script)

In [ ]:
# datadir='/home/krsharma/ClassificationImageText/trained_models/food101n_20e/robustnoiserank/eccvR_food-256d_emb'
datadir='/home/krsharma/ClassificationImageText/trained_models/clothing1m_10e/robustnoiserank/eccvR_clothing-256d_emb'
codedir='/home/krsharma/RobustNoiseRank'

conda activate faiss

for num in 190 100 500; do  # food - 40 30 50 100
    mkdir $datadir/ref$num
    
    python $codedir/main.py \
    --input_path=$datadir/cleannet_all_256d.tsv \
    --ref_input_path=$datadir/ref_$num.tsv \
    --list_k  50 100 250 500 1000 1500 2500 \ # food - 10 20 30 50 100 250 \
    --list_alpha 0.5 --list_bf 1.0 \
    --list_b 1 --list_e 2 \
    --save_path_dir=$datadir/results_$num/
done

# Evaluate Results of RobustNoiseRank

In [57]:
cleannet_all_256d = pd.read_csv(datadir + 'cleannet_all_256d.tsv', header=None, sep='\t')

cleannet_all_256d_df = cleannet_all_256d[[0, 1, 2]]

cleannet_all_256d_df.head()

everstore_mapping = dict(zip(cleannet_all_256d_df[0], cleannet_all_256d_df[1]))
everstore_mapping[0]

'GIPsEAWbm8NMUVECAOkij2nvJTQvbiMZAAAB'

In [58]:
ldf = pd.read_csv(labelfile, header=None)
dict_noisylabel = dict(zip(ldf[0], ldf[4]))
dict_everstorehandle = dict(zip(ldf[0], ldf[2]))
ldf.head()

0                          1  \
0   images/0/53/260975258,2323897053.jpg   260975258,2323897053.jpg   
1  images/3/61/2976764135,2716435361.jpg  2976764135,2716435361.jpg   
2  images/9/51/2289770356,3952390951.jpg  2289770356,3952390951.jpg   
3   images/9/46/430097811,2005980946.jpg   430097811,2005980946.jpg   
4   images/4/53/3469714287,432026453.jpg   3469714287,432026453.jpg   

                                      2        3   4    5           6     7  
0  GOotBwWSElDZtFsAAGshNhrA9hdEbiMZAAAB   Jacket   7  0.0  2020-02-04   val  
1  GProEQWGvjYQw6kAAK1c8Yf51zpabiMZAAAB   Jacket   7  0.0  2020-02-04   val  
2  GO3cCwUP8P3SX28AANt4RxtOHgYmbiMZAAAB  T-Shirt   0  NaN  2020-02-04  test  
3  GCAlEQWVFrN0SpECAJkqle41WVwlbiMZAAAB     Vest  12  NaN  2020-02-04  test  
4  GCKSEQVFfl_GL3kAANhTTwICHxdGbiMZAAAB    Dress  11  NaN  2020-02-04  test

In [59]:
val = ldf[ldf[7] == 'val']
len(val), val.head()

(7465,                                        0                          1  \
 0   images/0/53/260975258,2323897053.jpg   260975258,2323897053.jpg   
 1  images/3/61/2976764135,2716435361.jpg  2976764135,2716435361.jpg   
 5  images/0/61/2084697051,3460346061.jpg  2084697051,3460346061.jpg   
 6    images/4/45/1970005206,57268445.jpg    1970005206,57268445.jpg   
 7   images/9/45/3795980266,517718945.jpg   3795980266,517718945.jpg   
 
                                       2       3  4    5           6    7  
 0  GOotBwWSElDZtFsAAGshNhrA9hdEbiMZAAAB  Jacket  7  0.0  2020-02-04  val  
 1  GProEQWGvjYQw6kAAK1c8Yf51zpabiMZAAAB  Jacket  7  0.0  2020-02-04  val  
 5  GEMWEgUop6FFgmoAAJa94brcVmQrbiMZAAAB  Jacket  7  0.0  2020-02-04  val  
 6  GNi3DwVh9M2U95wAAIYARk8RzqpEbiMZAAAB  Jacket  7  0.0  2020-02-04  val  
 7  GOjYEAXTDWHbKNQAABY6FZpR1tgabiMZAAAB  Jacket  7  1.0  2020-02-04  val  )

In [60]:
def evalutil(detected):
    print(len(detected))

    # 342202 
    # 633645 k=250_a=0.5_bf=1.0_b=1.0_e=2.0.txt

    detected_noise_everstore = [everstore_mapping[d] for d in detected]
    print(detected_noise_everstore[0:5], len(detected_noise_everstore))

    print(detected[0:8])
    
    set_detected_noise = set(detected_noise_everstore)

    val['detected_label'] = val[2].apply(lambda x: 0.0 if x in set_detected_noise else 1.0)
    val.head()

    vlabels = np.array(val[5], dtype=np.int32)
    preds = np.array(val['detected_label'], dtype=np.int32)
    classes = np.array(val[4], dtype=np.int32)

    from sklearn.metrics import f1_score, classification_report, precision_recall_fscore_support

    def report_metrics(targets, preds, classes):
        C = np.max(classes) + 1
        per_class_accuracies = np.zeros((C,))
        for c in range(C):
            ind = np.where(classes == c)[0]
            class_acc = f1_score(targets[ind], preds[ind], average='micro')
            per_class_accuracies[c] = class_acc

        print('P/R/F1 (noise)', precision_recall_fscore_support(targets, preds, pos_label=0, average='binary'))
        print('f1_metrics (macro/unweighted mean)', f1_score(targets, preds, average='macro'))
        acc_classes = np.mean(per_class_accuracies)
        print('avg accuracy over classes', acc_classes, 'AvgErrorRate', 1 - acc_classes)

        report_additional = False
        if report_additional:
            print()
            acc = f1_score(targets, preds, average='micro')
            print('f1_metrics (accuracy/micro)', acc, 'ErrorRate', 1 - acc)
            print('P/R/F1 (clean)', precision_recall_fscore_support(targets, preds, pos_label=1, average='binary'))
            print('f1_metrics (weighted mean of f1)', f1_score(targets, preds, average='weighted'))
        # cr = classification_report(targets, preds)

    report_metrics(vlabels, preds, classes)
    
    

In [61]:
import os
from glob import glob

outpath = datadir
for subdir in glob(outpath + '*/'):
    print('-------------')
    for filename in os.listdir(subdir):
        print()
        print(subdir)
        print(filename)
        detected1 = np.loadtxt('{}/{}'.format(subdir, filename))
        evalutil(detected1)


-------------

/home/krsharma/ClassificationImageText/trained_models/clothing1m_10e/robustnoiserank/eccvR_clothing-256d_emb/results_500/
k=250_a=0.5_bf=1.0_b=1.0_e=2.0.txt
221992
['GJHZCwUaindpRcABADG_tneEdjoSbiMZAAAB', 'GB-b7QRaBz12tWIJAIamA13j518IbiMZAAAB', 'GK7VEQWTxrCv1KsAACiLUj3r4nNSbiMZAAAB', 'GH65EAXEFs9uYtUBAK5IWq9NpYtLbiMZAAAB', 'GGorAgVyQV-swUsIAPt5cJyssPBkbiMZAAAB'] 221992
[141846.   2288.  70691.  68205. 546514.  21453.  18420. 752970.]
P/R/F1 (noise) (0.7230401910067649, 0.6322199025748086, 0.674586968628179, None)
f1_metrics (macro/unweighted mean) 0.7454460568803685
avg accuracy over classes 0.7559934405929155 AvgErrorRate 0.2440065594070845

/home/krsharma/ClassificationImageText/trained_models/clothing1m_10e/robustnoiserank/eccvR_clothing-256d_emb/results_500/
k=2500_a=0.5_bf=1.0_b=1.0_e=2.0.txt


/home/krsharma/miniconda3/envs/cascade/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


461072
['GJHZCwUaindpRcABADG_tneEdjoSbiMZAAAB', 'GFTtEgUVauLJ8f8CAEptWfIc-I49biMZAAAB', 'GDR0EgU91lLcksoBAKo0Sll5HVwybiMZAAAB', 'GProBgV6m-OL1LoAAKge6Xf56PlnbiMZAAAB', 'GC1pEgVJCzQfOhABAJUSVN_uKSFdbiMZAAAB'] 461072
[ 141846.  228626.  814022.  997880.  650415.    2288. 1011535.  963521.]
P/R/F1 (noise) (0.5812843160658868, 0.8472512178148921, 0.6895087073481524, None)
f1_metrics (macro/unweighted mean) 0.7053746663726906
avg accuracy over classes 0.7145203445863038 AvgErrorRate 0.28547965541369624

/home/krsharma/ClassificationImageText/trained_models/clothing1m_10e/robustnoiserank/eccvR_clothing-256d_emb/results_500/
k=100_a=0.5_bf=1.0_b=1.0_e=2.0.txt
201899
['GJHZCwUaindpRcABADG_tneEdjoSbiMZAAAB', 'GB-b7QRaBz12tWIJAIamA13j518IbiMZAAAB', 'GCuBAgW6xzIGMpUAAEp1qUSnZ4JlbiMZAAAB', 'GK7VEQWTxrCv1KsAACiLUj3r4nNSbiMZAAAB', 'GLGlEgX_wE4CuNwMAC5dTESYBagGbiMZAAAB'] 201899
[141846.   2288.  21453.  70691. 752970. 546514. 639999. 879060.]
P/R/F1 (noise) (0.7404873877725524, 0.6026443980514962, 0.

# Give detected ranked list as everstore handles

In [68]:
odir = datadir + 'results_190/'
oname = 'k=250_a=0.5_bf=1.0_b=1.0_e=2.0.txt'
detected = np.loadtxt(odir + oname)


In [63]:
# cleannet_all_256d.tsv everstore (matches row number)

cleannet_all_256d = pd.read_csv(datadir + 'cleannet_all_256d.tsv', header=None, sep='\t')

cleannet_all_256d_df = cleannet_all_256d[[0, 1, 2]]

cleannet_all_256d_df.head()

everstore_mapping = dict(zip(cleannet_all_256d_df[0], cleannet_all_256d_df[1]))
everstore_mapping[0]

'GIPsEAWbm8NMUVECAOkij2nvJTQvbiMZAAAB'

In [64]:
cleannet_all_256d_df.head()

0                                     1   2
0  0  GIPsEAWbm8NMUVECAOkij2nvJTQvbiMZAAAB  13
1  1  GKHrDQWieLFkLXkJAIaDGKAkHzFAbiMZAAAB   0
2  2  GIubAgXFwnwkyr4BAIvraNOp1D9jbiMZAAAB   8
3  3  GN9QEgX1E50yB4IJAOP6qTt1_CNebiMZAAAB  12
4  4  GNKBDAV3PCNpAQgBAGejLVTPZyFrbiMZAAAB   7

In [65]:
len(detected)

266952

In [66]:
eranked = [everstore_mapping[d] for d in detected]
print(eranked[0:10], len(eranked))

['GJHZCwUaindpRcABADG_tneEdjoSbiMZAAAB', 'GB-b7QRaBz12tWIJAIamA13j518IbiMZAAAB', 'GFTtEgUVauLJ8f8CAEptWfIc-I49biMZAAAB', 'GK7VEQWTxrCv1KsAACiLUj3r4nNSbiMZAAAB', 'GProBgV6m-OL1LoAAKge6Xf56PlnbiMZAAAB', 'GJqrEAUkXxc16C4JAENBpy6Y-M8tbiMZAAAB', 'GH65EAXEFs9uYtUBAK5IWq9NpYtLbiMZAAAB', 'GMdnEQUFAQdb8XcAALCN1qz_5EVlbiMZAAAB', 'GGorAgVyQV-swUsIAPt5cJyssPBkbiMZAAAB', 'GC1pEgVJCzQfOhABAJUSVN_uKSFdbiMZAAAB'] 266952


In [69]:
np.savetxt('out.txt', eranked, fmt='%s')
np.savetxt(odir + 'out' + oname, eranked, fmt='%s')

# Results

In [ ]:
FOOD (ROUND-0)

WITH IMAGENET PRETRAINING

results_30

5P/R/F1 (noise) (0.39812992125984253, 0.8822246455834242, 0.5486605629026788, None)
f1_metrics (macro/unweighted mean) 0.6724628392348998
avg accuracy over classes 0.7185903864103752 AvgErrorRate 0.2814096135896248

10P/R/F1 (noise) (0.3869441816461684, 0.8920392584514721, 0.5397558561530847, None)
f1_metrics (macro/unweighted mean) 0.6617551564132343
avg accuracy over classes 0.7040161392502351 AvgErrorRate 0.2959838607497649

results_40
5P/R/F1 (noise) (0.40699442473390773, 0.8756815703380589, 0.5557093425605536, None)
f1_metrics (macro/unweighted mean) 0.6804638945812477
avg accuracy over classes 0.7282107586403482 AvgErrorRate 0.27178924135965177

10 P/R/F1 (noise) (0.4025403028822667, 0.8985823336968375, 0.5560053981106613, None)
f1_metrics (macro/unweighted mean) 0.6770514870271012
avg accuracy over classes 0.7207489675232696 AvgErrorRate 0.27925103247673044

results_50 *
5P/R/F1 (noise) (0.4117946110828673, 0.8833151581243184, 0.5617198335644938, None)
f1_metrics (macro/unweighted mean) 0.6850733147816408
avg accuracy over classes 0.7328569955055766 AvgErrorRate 0.2671430044944234

results_100
5P/R/F1 (noise) (0.423936170212766, 0.8691384950926936, 0.5698963174830175, None)
f1_metrics (macro/unweighted mean) 0.6949705970361983
avg accuracy over classes 0.745269233253319 AvgErrorRate 0.25473076674668105

10P/R/F1 (noise) (0.4117943548387097, 0.8909487459105779, 0.5632540503274733, None)
f1_metrics (macro/unweighted mean) 0.6853650588972118
avg accuracy over classes 0.7317169146044237 AvgErrorRate 0.2682830853955763


WITHOUT IMAGENET PRETRAINING

/home/krsharma/ClassificationImageText/trained_models/food101n_20e/robustnoiserank/eccvR_food-256d_emb/results_40/
k=10_a=0.5_bf=1.0_b=1.0_e=2.0.txt
102909
['GKNuAwUrW0Uij8YBADEtn3Yft0w6biMZAAAB', 'GB-b7QT5YtHA96sDANhdgJzV5CxkbiMZAAAB', 'GM-bEAVuW7Vw360BAMAnWufyev4gbiMZAAAB', 'GCCSEQXFZGhLTXMCAHffM814myVNbiMZAAAB', 'GGosEwWdC7yM_lUEAOyA0wSHdz8ubiMZAAAB'] 102909
[ 10315. 291272. 217971.  48794. 167911.  90199.  18152.  93281.]
P/R/F1 (noise) (0.40986908358509566, 0.8876772082878953, 0.5607991732690321, None)
f1_metrics (macro/unweighted mean) 0.6835003618283144
avg accuracy over classes 0.7291915600594527 AvgErrorRate 0.27080843994054726

Error Recall, F1, MacroF1
Paper NoiseRank (I) unsup. 24/18, 85.61 64.42 76.06 (actually similar to bottom row)
                           26.71, 88.33, 56.17, 68.51
No pretraining             27, 88,   56,   68

Clothing
NoiseRank (I) unsup. 23/22, 74.18 71.74 76.52
No pretraining       24/ ,  68.44,68.76,74.67 

In [ ]:
CLOTHING (ROUND - 0)

WIHTOUT IMAGENET PRETRAINING

/home/krsharma/ClassificationImageText/trained_models/clothing1m_10e/robustnoiserank/eccvR_clothing-256d_emb/results_190/
k=250_a=0.5_bf=1.0_b=1.0_e=2.0.txt
266952
['GJHZCwUaindpRcABADG_tneEdjoSbiMZAAAB', 'GB-b7QRaBz12tWIJAIamA13j518IbiMZAAAB', 'GFTtEgUVauLJ8f8CAEptWfIc-I49biMZAAAB', 'GK7VEQWTxrCv1KsAACiLUj3r4nNSbiMZAAAB', 'GProBgV6m-OL1LoAAKge6Xf56PlnbiMZAAAB'] 266952
[ 141846.    2288.  228626.   70691.  997880.   18420.   68205. 1011535.]
P/R/F1 (noise) (0.6909027046013347, 0.6844119693806542, 0.6876420206257648, None)
f1_metrics (macro/unweighted mean) 0.7467963605137728
avg accuracy over classes 0.7543342854671993 AvgErrorRate 0.24566571453280073

23.54
22.81

# Fine Tune Flows

In [ ]:
f171259422 (Clothing 73% round 0 denoised finetune parameters)
f132905000 (Food101N 85.78% round 1 denoised finetune parameters)


In [70]:
24.56 - 23.54

1.0199999999999996

In [ ]:
o 67\% (plain ResNet trained on noisy train set, without noise removal) from 68.94\% (with ImageNet pretraining). With label noise removal, using representations extracted from the new baseline model, the result was 72\%; compared to 73.82\% reported for the corresponding setting on the ResNet pretrained on ImageNet. The error rate for noise detection reduced by $1\%$.



In [75]:
71.7-67

4.700000000000003

In [72]:
73.82 - 68.94

4.8799999999999955

In [76]:
73.82-71.7

2.1199999999999903

In [79]:
68.94-67

1.9399999999999977

In [80]:
100 - 18.5

81.5

In [81]:
100 - 20.1

79.9

In [82]:
90-57

33